# Generated by Django 5.1.3 on 2025-01-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aadhaar',
            name='aadhaar_no',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
